const buttons = {};

Object.assign(buttons, {
  es: {
    shop: "SHOP 🛍️",
    pokerTrips: "POKER TRIPS & VIP ✈️🏨",
    buyTickets: "BUY TICKETS 🎟️",
    giveaways: "SORTEOS 🎁",
    games: "JUEGOS 🎮",
    calendar: "CALENDARIO DE TORNEOS 📅",
  },
  en: {
    shop: "SHOP 🛍️",
    pokerTrips: "POKER TRIPS & VIP ✈️🏨",
    buyTickets: "BUY TICKETS 🎟️",
    giveaways: "GIVEAWAYS 🎁",
    games: "GAMES 🎮",
    calendar: "TOURNAMENT CALENDAR 📅",
  },
  pt: {
    shop: "SHOP 🛍️",
    pokerTrips: "VIAGENS DE PÔQUER & VIP ✈️🏨",
    buyTickets: "COMPRAR INGRESSOS 🎟️",
    giveaways: "SORTEIOS 🎁",
    games: "JOGOS 🎮",
    calendar: "CALENDÁRIO DE TORNEIOS 📅",
  },
  fr: {
    shop: "BOUTIQUE 🛍️",
    pokerTrips: "VOYAGES POKER & VIP ✈️🏨",
    buyTickets: "ACHETER DES BILLETS 🎟️",
    giveaways: "TIRAGES AU SORT 🎁",
    games: "JEUX 🎮",
    calendar: "CALENDRIER DES TOURNOIS 📅",
  },
  de: {
    shop: "SHOP 🛍️",
    pokerTrips: "POKER-REISEN & VIP ✈️🏨",
    buyTickets: "TICKETS KAUFEN 🎟️",
    giveaways: "GEWINNSPIELE 🎁",
    games: "SPIELE 🎮",
    calendar: "TURNIERKALENDER 📅",
  },
  it: {
    shop: "NEGOZIO 🛍️",
    pokerTrips: "VIAGGI POKER & VIP ✈️🏨",
    buyTickets: "ACQUISTA BIGLIETTI 🎟️",
    giveaways: "ESTRAZIONI 🎁",
    games: "GIOCHI 🎮",
    calendar: "CALENDARIO TORNEI 📅",
  },
  ru: {
    shop: "МАГАЗИН 🛍️",
    pokerTrips: "ПОКЕР-ТУРЫ И VIP ✈️🏨",
    buyTickets: "КУПИТЬ БИЛЕТЫ 🎟️",
    giveaways: "РОЗЫГРЫШИ 🎁",
    games: "ИГРЫ 🎮",
    calendar: "КАЛЕНДАРЬ ТУРНИРОВ 📅",
  },
  ja: {
    shop: "ショップ 🛍️",
    pokerTrips: "ポーカートリップ & VIP ✈️🏨",
    buyTickets: "チケットを購入 🎟️",
    giveaways: "プレゼント企画 🎁",
    games: "ゲーム 🎮",
    calendar: "トーナメントカレンダー 📅",
  },
  zh: {
    shop: "商店 🛍️",
    pokerTrips: "撲克之旅 & VIP ✈️🏨",
    buyTickets: "購買門票 🎟️",
    giveaways: "抽獎活動 🎁",
    games: "遊戲 🎮",
    calendar: "錦標賽日曆 📅",
  },
  ar: {
    shop: "المتجر 🛍️",
    pokerTrips: "رحلات البوكر وكبار الشخصيات ✈️🏨",
    buyTickets: "شراء التذاكر 🎟️",
    giveaways: "سحوبات 🎁",
    games: "ألعاب 🎮",
    calendar: "جدول البطولات 📅",
  },
  ko: {
    shop: "상점 🛍️",
    pokerTrips: "포커 여행 & VIP ✈️🏨",
    buyTickets: "티켓 구매 🎟️",
    giveaways: "이벤트 🎁",
    games: "게임 🎮",
    calendar: "토너먼트 일정 📅",
  },
  tr: {
    shop: "MAĞAZA 🛍️",
    pokerTrips: "POKER SEYAHATLERİ & VIP ✈️🏨",
    buyTickets: "BİLET SATIN AL 🎟️",
    giveaways: "ÇEKİLİŞLER 🎁",
    games: "OYUNLAR 🎮",
    calendar: "TURNUVA TAKVİMİ 📅",
  },
  pl: {
    shop: "SKLEP 🛍️",
    pokerTrips: "PODRÓŻE POKEROWE & VIP ✈️🏨",
    buyTickets: "KUP BILETY 🎟️",
    giveaways: "ROZDAWANIE 🎁",
    games: "GRY 🎮",
    calendar: "KALENDARZ TURNIEJÓW 📅",
  },
  uk: {
    shop: "МАГАЗИН 🛍️",
    pokerTrips: "ПОКЕРНІ ПОДОРОЖІ & VIP ✈️🏨",
    buyTickets: "КУПИТИ КВИТКИ 🎟️",
    giveaways: "РОЗІГРАШІ 🎁",
    games: "ІГРИ 🎮",
    calendar: "КАЛЕНДАР ТУРНІРІВ 📅",
  },
  id: {
    shop: "TOKO 🛍️",
    pokerTrips: "PERJALANAN POKER & VIP ✈️🏨",
    buyTickets: "BELI TIKET 🎟️",
    giveaways: "HADIAH 🎁",
    games: "PERMAINAN 🎮",
    calendar: "KALENDER TURNAMEN 📅",
  },
  tl: {
    shop: "TINDIHAN 🛍️",
    pokerTrips: "POKER NA BIYAHE & VIP ✈️🏨",
    buyTickets: "BUMILI NG TIKET 🎟️",
    giveaways: "GIVEAWAYS 🎁",
    games: "LARO 🎮",
    calendar: "KALENDARYO NG PALIGSAHAN 📅",
  },
  cs: {
    shop: "OBCHOD 🛍️",
    pokerTrips: "POKEROVÉ CESTY & VIP ✈️🏨",
    buyTickets: "KOUPIT VSTUPENKY 🎟️",
    giveaways: "SOUTĚŽE 🎁",
    games: "HRY 🎮",
    calendar: "KALENDÁŘ TURNAJŮ 📅",
  },
  ro: {
    shop: "MAGAZIN 🛍️",
    pokerTrips: "EXCURSII POKER & VIP ✈️🏨",
    buyTickets: "CUMPĂRĂ BILETE 🎟️",
    giveaways: "CONCURSURI 🎁",
    games: "JOCURI 🎮",
    calendar: "CALENDAR TURNEE 📅",
  },
  sr: {
    shop: "PRODAVNICA 🛍️",
    pokerTrips: "POKER PUTOVANJA & VIP ✈️🏨",
    buyTickets: "KUPI KARTE 🎟️",
    giveaways: "NAGRADNE IGRE 🎁",
    games: "IGRE 🎮",
    calendar: "KALENDAR TURNIRA 📅",
  },
  bs: {
    shop: "TRGOVINA 🛍️",
    pokerTrips: "POKER PUTOVANJA & VIP ✈️🏨",
    buyTickets: "KUPI ULAZNICE 🎟️",
    giveaways: "NAGRADNE IGRE 🎁",
    games: "IGRE 🎮",
    calendar: "KALENDAR TURNIRA 📅",
  },
  he: {
    shop: "חנות 🛍️",
    pokerTrips: "טיולי פוקר & VIP ✈️🏨",
    buyTickets: "קניית כרטיסים 🎟️",
    giveaways: "הגרלות 🎁",
    games: "משחקים 🎮",
    calendar: "לוח טורנירים 📅",
  },
  vi: {
    shop: "CỬA HÀNG 🛍️",
    pokerTrips: "CHUYẾN ĐI POKER & VIP ✈️🏨",
    buyTickets: "MUA VÉ 🎟️",
    giveaways: "QUÀ TẶNG 🎁",
    games: "TRÒ CHƠI 🎮",
    calendar: "LỊCH GIẢI ĐẤU 📅",
  },
  mn: {
    shop: "ДЭЛГҮҮР 🛍️",
    pokerTrips: "ПОКЕР АЯЛАЛ & VIP ✈️🏨",
    buyTickets: "Тасалбар авах 🎟️",
    giveaways: "СУГАЛАА 🎁",
    games: "ТОГЛООМ 🎮",
    calendar: "ТЭМЦЭЭНИЙ ХУВААРЬ 📅",
  },
  bg: {
    shop: "МАГАЗИН 🛍️",
    pokerTrips: "ПОКЕР ПЪТУВАНИЯ & VIP ✈️🏨",
    buyTickets: "КУПИ БИЛЕТИ 🎟️",
    giveaways: "ТЕГЛЕНИЯ 🎁",
    games: "ИГРИ 🎮",
    calendar: "КАЛЕНДАР НА ТУРНИРИТЕ 📅",
  },
});

export default buttons;
